"""Add date coulmn to shifts model

Revision ID: 523b27493e46
Revises: 979f54ee54a0
Create Date: 2023-08-28 11:07:34.250505

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523b27493e46'
down_revision: Union[str, None] = '979f54ee54a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_unavailable_shifts', 'reason')
    op.add_column('shifts', sa.Column('date', sa.Date()))

    # Set a default date for existing rows (for demonstration purposes, set to today's date)
    op.execute(text("UPDATE shifts SET date = :default_date").bindparams(default_date=datetime.today().date()))

    # Now make the date column NOT NULL
    op.alter_column('shifts', 'date', nullable=False)
    op.alter_column('shifts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('shifts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('shifts', 'date')
    op.add_column('employee_unavailable_shifts', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
