"""Init emplyoee_unavailable_shofts table and adding relationship for shifts and employees tables

Revision ID: 979f54ee54a0
Revises: 7090731927b4
Create Date: 2023-08-27 14:26:59.347422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '979f54ee54a0'
down_revision: Union[str, None] = '7090731927b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employee_unavailable_shifts',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('employee_id', sa.Integer, sa.ForeignKey('employees.id'), nullable=False),
        sa.Column('shift_id', sa.Integer, sa.ForeignKey('shifts.id'), nullable=False),
        sa.Column('date', sa.Date, nullable=False),
        sa.Column('reason', sa.String, nullable=True)
    )
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee_unavailable_shifts")
    op.alter_column('employees', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
