"""Alter start and end time in shifts to time without timezone

Revision ID: acd1d44eff7a
Revises: 25eaf2a84c68
Create Date: 2023-08-20 21:04:19.001633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acd1d44eff7a'
down_revision: Union[str, None] = '25eaf2a84c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'start_time', existing_type=postgresql.TIMESTAMP(), type_=sa.Time())
    op.alter_column('shifts', 'end_time', existing_type=postgresql.TIMESTAMP(), type_=sa.Time())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'end_time', existing_type=sa.Time(), type_=postgresql.TIMESTAMP())
    op.alter_column('shifts', 'start_time', existing_type=sa.Time(), type_=postgresql.TIMESTAMP())
    # ### end Alembic commands ###
